enum ErrorEnum {
  // 400
  BAD_REQUEST = "BAD_REQUEST",
  SAME_TITLE = "SAME_TITLE",
  // 404
  PAGE_NOT_FOUND = "PAGE_NOT_FOUND",
  // 500
  BAD_CONNECTION = "BAD_CONNECTION",
  SERVER_ERROR = "SERVER_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",}

export { ErrorEnum };